#!/bin/bash

echo "⚰️ Detecting dead code..."
if ! make scan_dead_code; then
    echo "😵 Dead code found"
    exit 1
fi

echo "🔬 Executing tests..."
if ! make tests; then
    echo "😵 Tests failed"
    exit 1
fi

echo "🏗️ Building the app..."
if ! make build-release; then
    echo "😵 Build failed"
    exit 1
fi

echo "✅ Success!"
exit 0